backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "src/images/uploads" # Media files will be stored in the repo under src/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/views/index.njk"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: page_content, widget: markdown}
          - {label: Image, name: img_src, widget: image}
      - label: "Content"
        name: "content"
        file: "src/views/content.njk"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: page_content, widget: markdown}
          - {label: Image, name: img_src, widget: image}