backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "src/images/uploads" # Media files will be stored in the repo under src/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Pages"
    name: "pages"
    delete: false
    files:
      - label: "Home"
        name: "home"
        file: "src/views/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "content-page"}
          - {label: Image, name: image, widget: image}
          - {label: Title, name: title, widget: string}
          - {label: Content, name: body, widget: markdown}
      - label: "Contact"
        name: "contact"
        file: "src/views/contact.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "content-page"}
          - {label: Image, name: image, widget: image}
          - {label: Title, name: title, widget: string}
          - {label: Content, name: body, widget: markdown}